version: "3.8"

services:
  mask3d:
    image: lluisb3/mask3d:v7.0
    volumes:
      - /home/ither1/docker_volumes/hl2ss/hololens_docker/hololens_docker_pcd.ply:/home/app/data/raw/hesso/scene0001_00.ply
      - /home/ither1/docker_volumes/mask3d:/home/app/eval_output
    deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             count: 1
             capabilities: [gpu]
